# Generated by Django 3.1.2 on 2020-11-10 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 10, 25, 21, 562611)),
        ),
        migrations.AlterField(
            model_name='user_key',
            name='key',
            field=models.CharField(default='R3Nw9I1E0fZhC84', max_length=15),
        ),
    ]
