# Generated by Django 3.1.2 on 2020-11-10 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201110_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 10, 38, 57, 36565)),
        ),
        migrations.AlterField(
            model_name='user_key',
            name='key',
            field=models.CharField(default='OD4HwGDagKtB2mz', max_length=15),
        ),
    ]
