# Generated by Django 3.1.2 on 2020-10-24 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0002_auto_20201024_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ip',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 12, 14, 58, 366079)),
        ),
    ]
