# Generated by Django 3.1.2 on 2020-10-25 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_auto_20201024_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 9, 8, 43, 570981)),
        ),
    ]
