# Generated by Django 3.1.2 on 2020-10-25 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0005_auto_20201025_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='page',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 9, 25, 9, 988055)),
        ),
    ]
